name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-27ab8ccf-a2a3-4f23-9cff-d08c7f473e46.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ninocontainerregistry.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: my-container-app
          resourceGroup: rg-container-apps-demo
          imageToBuild: ninocontainerregistry.azurecr.io/my-container-app:${{ github.sha }}
          
            

     

